### ISSUE TITLE
Cannot View Customer Info - Too Few Arguments In Customer.php

### ISSUE THREAD

**Issue by drinkingsouls** [mailchimp/mc-magento2#1802]
### Preconditions

- Magento 2.4.6-p2
- PHP 8.1 & PHP 8.2
- Mailchimp Module 103.4.55

### Steps to reproduce

- Log in to Magento Dashboard
- Navigate to Customers > All Customers
- Click "Edit" for any customer.

### Actual and Expected result

**Expected Result**
Can Navigate customer tabs & info

**Actual Result**
Error is present:
Too few arguments to function Magento\Newsletter\Model\Subscriber\Interceptor::loadByCustomer(), 1 passed in /home/public/app/code/Ebizmarts/MailChimp/Block/Adminhtml/Customer/Edit/Tabs/View/Customer.php on line 58 and exactly 2 expected
Exception in /home/public/generated/code/Magento/Newsletter/Model/Subscriber/Interceptor.php:29

![errors](https://github.com/mailchimp/mc-magento2/assets/45666862/95127def-af38-451d-bf75-5a778598ffad)

### Additional information

This error is not present in v103.4.54. It has appeared since update to 103.4.55.
Issue on both my live and development server.

### Temp Workaround
Change Line 58 back to what was used in previous version:
`$subscriber->loadByCustomerId($customerId);`

The MailChimp Information Tab is empty for all customers too. Only the title "MailChimp Information" appears.
